services:
  - type: web
    name: tastebite-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false 