services:
  - type: web
    name: tastebite-backend
    env: python
    buildCommand: |
      rm -rf .git
      rm -rf __pycache__
      rm -rf */__pycache__
      rm -rf */*/__pycache__
      pip install --no-cache-dir -r requirements.txt
      python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false 