"""Add cascade delete constraints to user-related foreign keys

Revision ID: 1c84688e93be
Revises: a5316bbcfee9
Create Date: 2025-05-17 00:04:28.893680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c84688e93be'
down_revision = 'a5316bbcfee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('external_comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_comment_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_comment_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('external_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_favorite_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_favorite_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('external_rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_rating_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_rating_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorite_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_favorite_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_rating_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_rating_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorite_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_favorite_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('external_rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_rating_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_rating_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('external_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_favorite_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_favorite_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('external_comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_external_comment_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_external_comment_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
