"""Add sharing features

Revision ID: 46ac0694dbc5
Revises: 7fde8b17080c
Create Date: 2025-06-21 19:09:11.018564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ac0694dbc5'
down_revision = '7fde8b17080c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_column('recipe_ids')

    # ### end Alembic commands ###
