"""Add recipe_ids to ShoppingListItem

Revision ID: 7fde8b17080c
Revises: f1f374c04253
Create Date: 2025-06-21 18:53:52.723043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fde8b17080c'
down_revision = 'f1f374c04253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_column('recipe_ids')

    # ### end Alembic commands ###
