"""Add external recipe support

Revision ID: 91d2b8c224a6
Revises: c0dd17a1722e
Create Date: 2025-05-16 21:49:52.618531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d2b8c224a6'
down_revision = 'c0dd17a1722e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('external_id')
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
