"""add avatar column

Revision ID: add_avatar
Revises: 
Create Date: 2024-06-07 20:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_avatar'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('avatar', sa.Text(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('user', 'avatar') 