"""Add external recipe interactions

Revision ID: c0dd17a1722e
Revises: b666c4ec0326
Create Date: 2025-05-16 21:37:20.549321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dd17a1722e'
down_revision = 'b666c4ec0326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_external_comment_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_external_favorite_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'user_id', name='uq_external_favorite_user')
    )
    op.create_table('external_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_external_rating_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'user_id', name='uq_external_rating_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_rating')
    op.drop_table('external_favorite')
    op.drop_table('external_comment')
    # ### end Alembic commands ###
