"""Increase instructions column size

Revision ID: d9ece4116d7e
Revises: add_avatar
Create Date: 2025-06-08 21:16:33.931399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ece4116d7e'
down_revision = 'add_avatar'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_recipe'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_recipe', 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorite_recipe'), type_='foreignkey')
        batch_op.create_foreign_key('fk_favorite_recipe', 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingredient_recipe'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ingredient_recipe', 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rating_recipe'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rating_recipe', 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipe_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_recipe_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recipe_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_recipe', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_recipe'), 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredient_recipe', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ingredient_recipe'), 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorite_recipe', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_favorite_recipe'), 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_recipe', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_recipe'), 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
