"""Add is_checked to ShoppingListItem

Revision ID: f1f374c04253
Revises: 5f0365ce9520
Create Date: 2025-06-21 18:51:08.484128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f374c04253'
down_revision = '5f0365ce9520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_column('is_checked')

    # ### end Alembic commands ###
